<?php

namespace AppBundle\Repository;

/**
 * starratingsystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class starratingsystemRepository extends \Doctrine\ORM\EntityRepository
{
}
